export const NODE_ID = 'node_id'
export const LIST = 'list'
export const PAGE_NUMBER = 'page_number'
export const CURRENT_EVENT = 'current_event'
export const CURRENT_TYPE = 'current_type'
export  const  USER = 'user'
export  const  PLATFORMS = 'platforms'
